name: daylio
description: "Daylio - Personal Diary - A mobile application Flutter project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


#------------------------- PACKAGES -------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  curved_labeled_navigation_bar: ^2.0.2
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.2
  local_auth: ^2.2.0
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.27.1
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.5

#------------------------- ./ PACKAGES END -------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: ^3.0.1


#------------------------- FLUTTER -------------------------#
flutter:
  uses-material-design: true
  # LOCAL ASSETS
  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/emoji/
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  # LOCAL FONTS
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
